name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Create google-services.json from secret
      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      # Generate debug keystore (alternative approach)
      - name: Create debug keystore
        run: |
          # Try to decode from base64 first
          if [ ! -z "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" ]; then
            echo "Attempting to decode keystore from base64..."
            echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > app/debug.keystore
            # Verify the keystore
            if keytool -list -keystore app/debug.keystore -storepass android -alias androiddebugkey > /dev/null 2>&1; then
              echo "✅ Successfully decoded keystore from base64"
            else
              echo "❌ Failed to decode keystore, generating new one..."
              rm -f app/debug.keystore
            fi
          fi

          # Generate new keystore if decoding failed or no secret provided
          if [ ! -f app/debug.keystore ]; then
            echo "Generating new debug keystore..."
            keytool -genkey -v -keystore app/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
            echo "✅ Generated new debug keystore"
          fi

          # Verify final keystore
          ls -la app/debug.keystore
          keytool -list -keystore app/debug.keystore -storepass android

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build release
        run: ./gradlew assembleDebug
        env:
          # Environment variables override secrets.json values
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          #token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
